
#numpy

In [21]:
import numpy as np
import pandas as pd
from  numpy.random import randn

## This is numphy


In [4]:
import numpy as np
x =np.random.rand(5,2)

print(x)


[[0.23930426 0.94431876]
 [0.50124887 0.4253437 ]
 [0.47638689 0.8050785 ]
 [0.36551022 0.93036528]
 [0.5646413  0.22749907]]


In [8]:
y =np.arange(2,16,2)
print(y)

[ 2  4  6  8 10 12 14]


In [16]:
z = np.random.randint(1,100,25)
print(z)

[54 46 97 36 27 29 97 28 94 46 88 43 48 16 35 60  2 40 58 90 42  5  1 64
 71]


In [17]:
n=z.reshape(5,5)
print(n)

[[54 46 97 36 27]
 [29 97 28 94 46]
 [88 43 48 16 35]
 [60  2 40 58 90]
 [42  5  1 64 71]]


In [26]:
n.shape
print(n)

[[54 46 97 36 27]
 [29 97 28 94 46]
 [88 43 48 16 35]
 [60  2 40 58 90]
 [42  5  1 64 71]]


In [27]:
n.max()
n.argmax()


2

In [28]:
n.min()

1

In [30]:
n.argmin()

22

### This is pandas (series)

In [7]:
x=['a','b']#this is a list of python
y=[10,20]
z=np.array(y)
z
m=pd.Series(z,x)
m

a    10
b    20
dtype: int32

In [11]:
x=pd.Series([1,2,3,4,5],["japan","Usa","india","korea","italy"])
x

japan    1
Usa      2
india    3
korea    4
italy    5
dtype: int64

In [13]:
y=pd.Series([1,2,4,4,5],["japan","Usa","india","Africa","italy"])
y

japan     1
Usa       2
india     4
Africa    4
italy     5
dtype: int64

In [15]:
x['india']#x[2] also works

3

In [16]:
x+y# na fo the countries not present


Africa     NaN
Usa        4.0
india      7.0
italy     10.0
japan      2.0
korea      NaN
dtype: float64

### This is pandas (data frame)


In [33]:
df= pd.DataFrame(randn(3,3),["A","B","c"],['x','y','Z'])
df

x         y         Z
A -0.319381 -1.818190  1.012469
B -2.438498  1.222440  0.940618
c -0.181365 -0.502498 -0.919417

In [35]:
df['x']

A   -0.319381
B   -2.438498
c   -0.181365
Name: x, dtype: float64

In [47]:
df["M"]= df['x']+df['y']
df

x         y         Z         M
A -0.319381 -1.818190  1.012469 -2.137572
B -2.438498  1.222440  0.940618 -1.216058
c -0.181365 -0.502498 -0.919417 -0.683863

In [7]:

from sklearn.tree import DecisionTreeClassifier
import pandas as pd

In [9]:
df=pd.read_csv("music.csv")
df

age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [12]:
x=df.drop(columns=["genre"])
y=df["genre"]

In [15]:
model=DecisionTreeClassifier()
model.fit(x,y)
predictions=model.predict([[21,1],[22,0]])
predictions

C:\Users\kisha\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array(['HipHop', 'Dance'], dtype=object)

# DataFrame Operations

In [6]:
import numpy as np
import pandas as pd
from  numpy.random import randn

In [8]:
arr=pd.DataFrame(randn(5,5),['A','B','C','D','E'],["KA",'MH','AP','KL','GL'])#creating a dataframe of random digit

In [9]:
arr

KA        MH        AP        KL        GL
A -1.388011 -0.215487 -0.641433  0.226460 -0.135913
B -0.324993  0.337643  1.714788 -0.962047  0.035393
C  1.244341  1.880112  0.677488  0.979616  1.088491
D  1.367433 -1.037584 -0.354604 -0.239065 -0.770719
E -0.668706  0.806593  1.827682 -0.084111 -0.647606

In [12]:
arr[arr>0] #just asigining a value of dataframe to the condition

KA        MH        AP        KL        GL
A       NaN       NaN       NaN  0.226460       NaN
B       NaN  0.337643  1.714788       NaN  0.035393
C  1.244341  1.880112  0.677488  0.979616  1.088491
D  1.367433       NaN       NaN       NaN       NaN
E       NaN  0.806593  1.827682       NaN       NaN

In [13]:
arr

KA        MH        AP        KL        GL
A -1.388011 -0.215487 -0.641433  0.226460 -0.135913
B -0.324993  0.337643  1.714788 -0.962047  0.035393
C  1.244341  1.880112  0.677488  0.979616  1.088491
D  1.367433 -1.037584 -0.354604 -0.239065 -0.770719
E -0.668706  0.806593  1.827682 -0.084111 -0.647606

In [19]:
ram["KA"]

C    1.244341
D    1.367433
Name: KA, dtype: float64

In [21]:
arr[arr["KA"]>0] #calling the only rows where the condition is true

KA        MH        AP        KL        GL
C  1.244341  1.880112  0.677488  0.979616  1.088491
D  1.367433 -1.037584 -0.354604 -0.239065 -0.770719

In [22]:
ram=arr[arr["KA"]>0] 

In [23]:
ram["KA"]

C    1.244341
D    1.367433
Name: KA, dtype: float64

In [25]:
arr

KA        MH        AP        KL        GL
A -1.388011 -0.215487 -0.641433  0.226460 -0.135913
B -0.324993  0.337643  1.714788 -0.962047  0.035393
C  1.244341  1.880112  0.677488  0.979616  1.088491
D  1.367433 -1.037584 -0.354604 -0.239065 -0.770719
E -0.668706  0.806593  1.827682 -0.084111 -0.647606

In [27]:
arr["PRICE"]=[130.3,141.3,154.7,172.4,191.77]

In [28]:
arr

KA        MH        AP        KL        GL   PRICE
A -1.388011 -0.215487 -0.641433  0.226460 -0.135913  130.30
B -0.324993  0.337643  1.714788 -0.962047  0.035393  141.30
C  1.244341  1.880112  0.677488  0.979616  1.088491  154.70
D  1.367433 -1.037584 -0.354604 -0.239065 -0.770719  172.40
E -0.668706  0.806593  1.827682 -0.084111 -0.647606  191.77

In [29]:
arr.set_index("PRICE")#just for practice

KA        MH        AP        KL        GL
PRICE                                                   
130.30 -1.388011 -0.215487 -0.641433  0.226460 -0.135913
141.30 -0.324993  0.337643  1.714788 -0.962047  0.035393
154.70  1.244341  1.880112  0.677488  0.979616  1.088491
172.40  1.367433 -1.037584 -0.354604 -0.239065 -0.770719
191.77 -0.668706  0.806593  1.827682 -0.084111 -0.647606

In [32]:
arr[(arr["KA"]>1 & (arr["MH"]>1))]

KA        MH        AP        KL        GL  PRICE
C  1.244341  1.880112  0.677488  0.979616  1.088491  154.7
D  1.367433 -1.037584 -0.354604 -0.239065 -0.770719  172.4

In [33]:
arr

KA        MH        AP        KL        GL   PRICE
A -1.388011 -0.215487 -0.641433  0.226460 -0.135913  130.30
B -0.324993  0.337643  1.714788 -0.962047  0.035393  141.30
C  1.244341  1.880112  0.677488  0.979616  1.088491  154.70
D  1.367433 -1.037584 -0.354604 -0.239065 -0.770719  172.40
E -0.668706  0.806593  1.827682 -0.084111 -0.647606  191.77